#!/usr/bin/env bash
#
# This is the script that builds the project documentation into ../docs.
#
# If you are using MkDocs from Anaconda, you will need to have the right conda
# environment activated before you run this.

mkdocs build
rm -rf ../docs/*
cp -R _site/* ../docs
